name: voyager_bloc
description: A BLoC plugin for Voyager. Allows describing used Blocs and their initial state in YAML config.
version: 3.0.2
homepage: https://github.com/vishna/voyager_bloc
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  voyager:
    git:
      url: https://github.com/eyeem/voyager.git
      ref: v3.0.2
  flutter_bloc: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
