name: voyager_bloc
description: A BLoC plugin for Voyager. Allows describing used Blocs and their initial state in YAML config.
version: 0.5.0
homepage: https://github.com/vishna/voyager_bloc

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  voyager: ^2.0.0
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

